spring:
  #静态资源处理
  resources:
    #启动默认静态资源处理，默认启用
    add-mappings: true
    cache:
      cachecontrol:
        #缓存相应时间，单位秒
        max-age: 3600
    chain:
      #资源链启动缓存，默认启动
      cache: true
      #启用资源链，默认禁用
      enabled: true
      #启用压缩资源(gzip,brotli)解析，默认禁用
      compressed: true
      #启用h5应用缓存，默认禁用
      html-application-cache: true
    static-locations: classpath:/static/
  #  关闭themeleaf的缓存
  thymeleaf:
    cache: false
    #redis配置
  redis:
      #服务器地址
    host: 47.107.230.131
      #端口
    port: 6379
      #数据库
    database: 0
      #超时时间
    timeout: 10000ms
      #密码
    lettuce:
      pool:
          #最大连接数，默认8
        max-active: 8
          #最大连接阻塞等待时间，默认-1
        max-wait: 10000ms
          #最大空闲连接，默认8
        max-idle: 200
          #最小空闲连接，默认0
        min-idle: 5
    password: 123456


  #    数据源配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 541788dz
    hikari:
      #      连接池名
      pool-name: DatahikariCP
      #      最小空闲连接数
      minimum-idle: 5
#      空闲链接最大连接时间默认600000（10分钟）
      idle-timeout: 1800000
#      从连接池返回的链接自动提交
      auto-commit: true
      #      最大存活时间 默认3000000（30分钟）
      max-lifetime: 1800000
#      链接超时时间默认30秒
      connection-timeout: 30000
#      心跳查询 检查连接是否可用的查询语句
      connection-test-query: SELECT 1
  mail:
    username: 3267919396@qq.com
    password: hylsbgtrleukcicj
    protocol: smtps
    host: smtp.qq.com
    port: 465



mybatis-plus:
#  配置Mapper.xml
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.dong.pojo
  global-config:
    db-config:
      id-type: auto
#  mybatis sql打印（方法接口的包，不是mapper.xml）
logging:
  level:
    com.dong.mapper: debug


